version: '3.8'

services:
  gateway-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - banku-network

networks:
  banku-network:
    driver: bridge 